### ISSUE TITLE
importOrder control not working

### ISSUE THREAD

**Issue by jorgepedraza88** [IanVS/prettier-plugin-sort-imports#53] opened 2023-02-13 11:29 UTC
**Your Environment**

-   Prettier: 2.8.3
-   Node 19.5.0
-   npm 9.3.1
-   Vscode

```
// prettier json
{
  "singleQuote": true,
  "trailingComma": "none",
  "importOrder": [
    "^react", 
    "<THIRD_PARTY_MODULES>", 
    "", 
    "^@(.*)", 
    "^[./]"],
  "importOrderSeparation": false,
  "plugins": ["@ianvs/prettier-plugin-sort-imports"]
}
```

```
import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import HomepageFeatures from '@site/src/components/HomepageFeatures';
import Layout from '@theme/Layout';
import styles from './index.module.css';
```

I'm trying to set a custom order of imports, and it's not working as expected.
Reading the docs, says that using an empty string in the importOrder array, it will set a new empty line.
As you can see in the file, there is not any empty line between imports. 
Thanks for your help.

**Comment by IanVS** [comment] 2023-02-13 13:52
Hi, can you please share a minimal reproduction?  I'm not able to reproduce the problem in our end-to-end tests, see: https://github.com/IanVS/prettier-plugin-sort-imports/blob/custom-order-sep-test/tests/WIP/__snapshots__/__snapshots__/ppsi.spec.js.snap.

**Comment by fbartho** [comment] 2023-02-14 17:14
@jorgepedraza88 are you sure VSCode is using Prettier for you? You didn’t commit your VSCode settings.json and that setting could also be in your global config.

It’s common for VSCode to use its own formatting instead of using prettier until you adjust the right setting.

A way to confirm would be to run prettier manually on your relevant source file instead.

**Comment by jorgepedraza88** [comment] 2023-02-15 14:02
@fbartho Everytime I save I can see in the console how Prettier is working.
`["INFO" - 14:57:50] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used`
`["INFO" - 14:57:50] Formatting completed in 36ms.`

Someone in my team test it and for him, it's working fine. I'm trying to figure it out why it's not working on my computer.

**Comment by jorgepedraza88** [comment] 2023-02-22 14:49
Reproduced by 3 members of my team, but only works with 1 of them. Can't figure out what is happening.

**Comment by IanVS** [comment] 2023-02-22 15:09
@jorgepedraza88 are you running prettier via the CLI or in an editor?

**Comment by jorgepedraza88** [comment] 2023-04-11 08:28
> @jorgepedraza88 are you running prettier via the CLI or in an editor?

Sorry for the late reply, I'm running it from the VScode editor.

**Comment by IanVS** [comment] 2023-04-11 11:26
You could be getting an interaction with the typescript "organize imports" setting, then.  Please try on the CLI directly to isolate.  If it works fine in the CLI, then it's an issue with your editor settings.  I'm pretty sure that's what's happening, so I'll close this for now, but let me know if you get failures when running prettier on its own.

**Closed by IanVS** 2023-04-11 11:26 UTC
Labels: needs reproduction
