### ISSUE TITLE
Sorts not being applied on .prettierrc.js

### ISSUE THREAD

**Issue by FranciscoKloganB** [IanVS/prettier-plugin-sort-imports#33] opened 2022-07-24 20:43 UTC
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: v16.5
-   **package manager**: 8.5.5
-   **IDE**: [VScode, CLI]

**Describe the bug**

When a file is `.prettierrc` imports are sorted. When the file is `.prettierrc.js` imports are not sorted.

**Expected behavior**

Given a `.prettierrc.js` file imports should be sorted.
However, this only appears to work when using `.prettierrc` as a `JSON` or `json5` file.

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```javascript
// .prettierrc.js
module.exports = {
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "",
    "^~/clients/(.*)$",
    "^~/components/(.*)$",
    "^~/config/(.*)$",
    "^~/cypress/(.*)$",
    "^~/hooks/(.*)$",
    "^~/layouts/(.*)$",
    "^~/locales/(.*)$",
    "^~/mocks/(.*)$",
    "^~/pages/(.*)$",
    "^~/providers/(.*)$",
    "^~/public/(.*)$",
    "^~/server/(.*)$",
    "^~/styles/(.*)$",
    "^~/themes/(.*)$",
    "^~/types/(.*)$",
    "^~/utils/(.*)$",
    "",
    "^[./]",
    "^[../]",
    ""
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  jsxBracketSameLine: false,
  plugins: [require("prettier-plugin-tailwindcss")],
  printWidth: 100,
  semi: false,
  singleQuote: false,
  trailingComma: "none"
}
```

**Error log**

Tried using `VSCode` format on save and `CLI`. Both runs terminate successfully, but imports are not sorted.

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

**Comment by FranciscoKloganB** [comment] 2022-07-24 21:05
it appears the issue has nothing to do with this or the "parent" prettier plugin but rather an incompatibility between two plugins for prettier. See [here](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9#issuecomment-1157359437).

**Comment by IanVS** [comment] 2022-07-25 15:22
Thanks for finding the issue and reporting back.  I don't think there's anything we can do for now, and https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31 seems to be where the activity is happening.  I'm going to close this for now, since it's not a bug in this plugin _per se_, but thanks again for bringing it up.

**Closed by IanVS** 2022-07-25 15:22 UTC

**Comment by IanVS** [comment] 2022-07-25 15:23
Also, we're tracking this in https://github.com/IanVS/prettier-plugin-sort-imports/issues/27 as well.
